add tests and CheckList for MoodPanda
Ladauser/MoodPanda pull request #1
Opened 2021-11-23 14:42 UTC by Ladauser

2021-11-27 06:43 UTC, vchesnakoutest requested changes

2021-11-27 06:43 UTC, vchesnakoutest commented on src/main/java/pages/AvatarPage.java
> +    public boolean checkMyAvatar() {
isMyAvatarDisplayed

2021-11-27 06:43 UTC, vchesnakoutest commented on src/main/java/pages/MyDiaryPage.java
> +    public String dateFromMyDiary() {
getDateFromMyDiary

2021-11-27 06:43 UTC, vchesnakoutest commented on src/main/java/pages/RateYourHappinessModalPage.java
> +    public static final String DAYS_OF_MONTH_CONTENT_CSS = "#ui-datepicker-div > table > tbody > tr > td > a";
такого плана локаторы конечно совсем не стабильные :)

2021-11-27 06:43 UTC, vchesnakoutest commented on src/test/java/BaseTest.java
> +        clickButtonsSteps = new ClickButtonsSteps();
на будущее: инициализацию страниц можно выносить тоже в отдельный метод

2021-11-27 06:43 UTC, vchesnakoutest commented on src/main/java/pages/FeedPage.java
> +    }
на будущее: все элементы хидера тоже можно выносить на отд. страницу HeaderPage (т.к. эти элементы будут общими для всех страниц). Соотв. наследование будет FeedPage > HeaderPage > BasePage.
![image](https://user-images.githubusercontent.com/48148401/143671101-d68c2381-c68b-4e32-baba-f10542f68284.png)

2021-11-29 11:38 UTC, Ladauser commented on src/main/java/pages/AvatarPage.java
> +    public boolean checkMyAvatar() {
исправила

2021-11-29 11:39 UTC, Ladauser commented on src/main/java/pages/MyDiaryPage.java
> +    public String dateFromMyDiary() {
исправила

2021-11-29 12:08 UTC, merged